version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
#    restart: unless-stopped
    env_file:
      - ./env/docker.env
      - ./env/bot.env
      - ./env/postgres.env
      - ./env/settings.env
    volumes:
      - ./logs/:/app/logs
      - ./backups/:/app/backups
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["python", "main.py"]
